checker:
  input_file: /mnt/work/code/extractor/DATA/小作物播种面积调整-12.9.xlsx
  output_log_file: /mnt/work/code/extractor/DATA/小作物播种面积地区数据调整日志.xlsx
  output_adjusted_file: /mnt/work/code/extractor/DATA/小作物播种面积地区数据调整结果.xlsx
  #  input_file: /Volumes/BinchenCoder/项目/LIULING/小作物播种面积调整-12.8.xlsx
  #  output_log_file: /Volumes/BinchenCoder/项目/LIULING/2022_crop_sown_area_adjusted_log-1.xlsx
  #  output_adjusted_file: /Volumes/BinchenCoder/项目/LIULING/2022_crop_sown_area_adjusted_all_crops_and_provinces-1.xlsx

  # 所有数值保留小数位数
  ROUND_DECIMAL: 6

ratio:
  # 调整比例阈值
  RATIO_MIN_PROVINCE: 0.998
  RATIO_MAX_PROVINCE: 1.002

  RATIO_MIN_1: 0.99
  RATIO_MAX_1: 1.01
  RATIO_MIN_2: 0.90
  RATIO_MAX_2: 1.10
  RATIO_MAX_3: 1.50