checker:
  input_file: /mnt/work/code/extractor/DATA/小作物播种面积调整-13省.xlsx
  output_log_file: /mnt/work/code/extractor/DATA/2022_crop_sown_area_adjusted_log.xlsx
  output_adjusted_file: /mnt/work/code/extractor/DATA/2022_crop_sown_area_adjusted_all_crops_and_provinces.xlsx

  # 所有数值保留小数位数
  ROUND_DECIMAL: 5

ratio:
  # 调整比例阈值
  RATIO_MIN_PROVINCE: 0.95
  RATIO_MAX_PROVINCE: 1.05

  RATIO_MIN_1: 0.99
  RATIO_MAX_1: 1.01
  RATIO_MIN_2: 0.90
  RATIO_MAX_2: 1.10


